### ISSUE TITLE
Unit Tests are broken

### ISSUE THREAD

**Issue by paladinu** [alicommit-malp/Redis.Net#1]
When I clone the repo fresh and try to run the unit tests, Async_CompressWithGzip_returnGzippedVersion and CompressWithGzip_returnGzippedVersion both fail.   

  Message: 
Assert.Equal() Failure
                                 ↓ (pos 26)
Expected: ···SE64####H4sIAAAAAAAAE3y9W5Mcx7E0+FfG9PwVrO+XfRsBQwkSARKCCNnuf···
Actual:   ···SE64####H4sIAAAAAAAACoS92ZJk13Et+CtlfL4Bi3noNw6gKIqDJEiidfd9O···
                                 ↑ (pos 26)

**Comment by alicommit-malp** [comment]
Sorry for the late response , I fixed the issue :)

**Comment by paladinu** [comment]
No worries, thanks!
